# Generated by Django 2.2.9 on 2020-01-06 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20200106_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must only have numbers, letters', regex='[a-zA-Z0-9]+')]),
        ),
    ]
