# Generated by Django 2.2.9 on 2020-01-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200106_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='polls',
        ),
    ]
