# Generated by Django 2.2.9 on 2020-01-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_voter_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_voting_node',
            field=models.BooleanField(default=True, help_text='Set to true when the user is used in a voting node', verbose_name='User is used as voting node'),
        ),
    ]
