# Generated by Django 2.2.9 on 2020-01-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0008_user_is_voting_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField()),
                ('true_counter', models.IntegerField(default=0)),
                ('false_counter', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Poll')),
            ],
            options={
                'unique_together': {('poll', 'question')},
            },
        ),
    ]
