# Generated by Django 2.2.9 on 2020-01-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0007_remove_voter_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('token', models.CharField(max_length=15)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Voter')),
            ],
        ),
    ]
